export enum PATH {
  MAIN = '/',
  LOGIN = 'login',
  SIGNUP = 'signup',
  MOVIES = 'movies',
  MOVIE = 'movie',
  POPULAR = 'popular',
  TRENDING = 'trending',
  TVSHOWS = 'tvshows',
  TVSHOW = 'tvshow',
  PEOPLE = 'people',
  SEARCH = 'search',
  ERROR = '404',
  WRONG_PAGE = '*',
}
