export enum PATH {
  START_PAGE = '/',
  LOGIN = 'login',
  SIGNUP = 'signup',
  MOVIES = 'movies',
  MOVIE = 'movie',
  POPULAR = 'popular',
  TRENDING = 'trending',
  TV_SHOWS = 'tv_shows',
  TV_SHOW = 'tv_show',
  PEOPLE = 'people',
  SEARCH = 'search',
  ERROR = '404',
  WRONG_PAGE = '*',
}
