export enum APP_ACTIONS {
  SET_APP_INITIALIZED_TRUE = 'appReducer/SET_APP_INITIALIZED_TRUE',
  SET_APP_INITIALIZED_FALSE = 'appReducer/SET_APP_INITIALIZED_FALSE',
  SET_APP_CONTENT_INITIALIZED_TRUE = 'appReducer/SET_APP_CONTENT_INITIALIZED_TRUE',
  SET_APP_CONTENT_INITIALIZED_FALSE = 'appReducer/SET_APP_CONTENT_INITIALIZED_FALSE',
}
