export enum MAIN_ACTIONS {
  SET_WHATS_POPULAR_FILTER = 'mainReducer/SET_WHATS_POPULAR_FILTER',
  SET_TRENDING_FILTER = 'mainReducer/SET_TRENDING_FILTER',
  SET_TRENDING_TIME_FILTER = 'mainReducer/SET_TRENDING_TIME_FILTER',
  SET_SEARCH_IMAGE_LINK = 'mainReducer/SET_SEARCH_IMAGE_LINK',
}
